name: Install and validate the package
description: Install and validate the package

inputs:
  pkg-name:
    description: Package name to import
    required: true
  pip-flags:
    description: Additional pip install flags
    required: false
    default: ""

runs:
  using: "composite"
  steps:
  - name: Install package - archive
    working-directory: ./dist
    run: |
      pip install *.tar.gz ${{ inputs.pip-flags }}
      pip list | grep lightning
      PKG_NAME=$(python -c "print({'app': 'lightning_app', 'lite': 'lightning_lite', 'pytorch': 'pytorch_lightning', 'lightning': 'lightning'}['${{matrix.pkg-name}}'])")
      python -c "import ${PKG_NAME}; print(${PKG_NAME}.__version__)"
    shell: bash

  - name: Install package - wheel
    working-directory: ./dist
    run: |
      pip install *.whl ${{ inputs.pip-flags }}
      pip list | grep lightning
      PKG_NAME=$(python -c "print({'app': 'lightning_app', 'lite': 'lightning_lite', 'pytorch': 'pytorch_lightning', 'lightning': 'lightning'}['${{matrix.pkg-name}}'])")
      python -c "import ${PKG_NAME}; print(${PKG_NAME}.__version__)"
    shell: bash
