name: Install and validate the package
description: Install and validate the package

inputs:
  pkg-name:
    description: package name for import
    required: true
  pip-flags:
    description: additional pil install flags
    required: false
    default: ""

defaults:
  run:
    shell: bash

runs:
  using: "composite"
  steps:
  - name: Install package - archive
    working-directory: ./dist
    run: |
      pip install *.tar.gz ${{ inputs.pip-flags }}
      pip list | grep lightning
      python -c "import ${{ inputs.pkg-name }}; print(${{ inputs.pkg-name }}.__version__)"

  - name: Install package - wheel
    working-directory: ./dist
    run: |
      pip install *.whl ${{ inputs.pip-flags }}
      pip list | grep lightning
      python -c "import ${{ inputs.pkg-name }}; print(${{ inputs.pkg-name }}.__version__)"
