name: Install and validate the package
description: Install and validate the package

inputs:
  pkg-name:
    description: Package name to import
    required: true
  pip-flags:
    description: Additional pip install flags
    required: false
    default: ""

runs:
  using: "composite"
  steps:
  - name: Choose package import
    run: |
      python -c "print('PACKAGE_NAME=' + {'app': 'lightning_app', 'lite': 'lightning_lite', 'pytorch': 'pytorch_lightning', 'lightning': 'lightning'}['${{matrix.pkg-name}}'])" >> $GITHUB_ENV
    shell: bash

  - name: Install package - archive
    working-directory: ./dist
    run: |
      pip install *.tar.gz ${{ inputs.pip-flags }}
      pip list | grep lightning
      python -c "import ${{ env.PACKAGE_NAME }}; print(${{ env.PACKAGE_NAME }}.__version__)"
    shell: bash

  - name: Install package - wheel
    working-directory: ./dist
    run: |
      pip install *.whl ${{ inputs.pip-flags }}
      pip list | grep lightning
      python -c "import ${{ env.PACKAGE_NAME }}; print(${{ env.PACKAGE_NAME }}.__version__)"
    shell: bash
