approvals:
  # check will fail if there is no approval
  minimum: 1
  groups:
    - name: GridAI
      minimum: 1
      from:
        - awaelchli
        - Borda
        - carmocca
        - edenlightning
        - ethanwharris
        - kaushikb11
        - krshrimali
        - rohitgr7
        - tchaton
        - williamFalcon
