subprojects:
  - id: pytorch_lightning
    paths:
      - ".circleci/**"
      - ".azure/**"
      - "docs/source-pytorch/**"
      # examples don't need to be added because they aren't used in CI, but these are
      - "examples/test_pl_examples.py"
      - "examples/run_ddp_examples.sh"
      - "examples/run_pl_examples.sh"
      - "requirements/pytorch/**"
      - "src/pytorch_lightning/**"
      - "setup.cfg"  # includes pytest config
      - "pyproject.toml"  # includes mypy config
    checks:
      - "check / schema"
      - "conda (3.8, 1.10)"
      - "conda (3.8, 1.9)"
      - "conda (3.9, 1.11)"
      - "conda (3.9, 1.12)"
      - "cpu (macOS-11, 3.10, latest, stable)"
      - "cpu (macOS-11, 3.7, latest, stable)"
      - "cpu (macOS-11, 3.7, oldest, stable)"
      - "cpu (ubuntu-20.04, 3.10, latest, stable)"
      - "cpu (ubuntu-20.04, 3.7, latest, stable)"
      - "cpu (ubuntu-20.04, 3.7, oldest, stable)"
      - "cpu (windows-2022, 3.10, latest, stable)"
      - "cpu (windows-2022, 3.7, latest, stable)"
      - "cpu (windows-2022, 3.7, oldest, stable)"
      - "doctest (pytorch)"
      - "make-docs (pytorch)"
      - "mypy"
      - "PR Gatekeeper (pytorch)"
      - "pytest (macOS-11, 3.8, latest)"
      - "pytest (macOS-11, 3.8, oldest)"
      - "pytest (ubuntu-20.04, 3.8, latest)"
      - "pytest (ubuntu-20.04, 3.8, oldest)"
      - "pytest (windows-2022, 3.8, latest)"
      - "pytest (windows-2022, 3.8, oldest)"
      - "pytorch-lightning (GPUs)"
      - "pytorch-lightning (GPUs) (testing PyTorch - stable)"
      - "pytorch-lightning (HPUs)"
      - "pytorch-lightning (IPUs)"
      - "slow (macOS-11, 3.7, 1.11)"
      - "slow (ubuntu-20.04, 3.7, 1.11)"
      - "slow (windows-2022, 3.7, 1.11)"
      - "test-on-tpus"

  - id: pytorch_lightning dockers
    paths:
      - "dockers/**"
    checks:
      - "build-conda (3.8, 1.10)"
      - "build-conda (3.8, 1.9)"
      - "build-conda (3.9, 1.11)"
      - "build-conda (3.9, 1.12)"
      - "build-cuda (3.8, 1.9, 11.1.1)"
      - "build-cuda (3.9, 1.10, 11.3.1)"
      - "build-cuda (3.9, 1.11, 11.3.1)"
      - "build-cuda (3.9, 1.12, 11.3.1)"
      - "build-cuda (3.9, 1.9, 11.1.1)"
      - "build-hpu (1.5.0, 1.11.0)"
      - "build-ipu (3.9, 1.9)"
      - "build-NGC"
      - "build-pl (3.9, 1.10, 11.3.1)"
      - "build-pl (3.9, 1.11, 11.3.1)"
      - "build-pl (3.9, 1.12, 11.3.1)"
      - "build-pl (3.9, 1.9, 11.1.1)"
      - "build-xla (3.7, 1.12)"

  - id: lightning_app
    paths:
      - "TODO"
    checks:
      - "TODO"

  - id: ci
    paths:
      - ".actions/setup_tools.py"
      - "assistant.py"
      - ".github/**"
      - ".pre-commit-config.yaml"
      - "setup.py"
    checks:
      - "install-meta-pypi (macOS-11, 3.8)"
      - "install-meta-pypi (ubuntu-20.04, 3.8)"
      - "install-meta-pypi (windows-2022, 3.8)"
      - "install-meta-src (macOS-11, 3.8)"
      - "install-meta-src (macOS-11, lightning, 3.8)"
      - "install-meta-src (ubuntu-20.04, 3.8)"
      - "install-meta-src (ubuntu-20.04, lightning, 3.8)"
      - "install-meta-src (windows-2022, 3.8)"
      - "install-meta-src (windows-2022, lightning, 3.8)"
      - "install-standalone (macOS-11, app, 3.8)"
      - "install-standalone (macOS-11, pytorch, 3.8)"
      - "install-standalone (ubuntu-20.04, app, 3.8)"
      - "install-standalone (ubuntu-20.04, pytorch, 3.8)"
      - "install-standalone (windows-2022, app, 3.8)"
      - "install-standalone (windows-2022, pytorch, 3.8)"

  - id: all
    paths:
      - "**"
    checks:
      - "WIP"
