subprojects:
  - id: pytorch_lightning
    paths:
      - ".circleci/**"
      - ".azure/**"
      - "docs/source-pytorch/**"
      # examples don't need to be added because they aren't used in CI, but these are
      - "examples/test_pl_examples.py"
      - "examples/run_ddp_examples.sh"
      - "examples/run_pl_examples.sh"
      - "requirements/pytorch/**"
      - "src/pytorch_lightning/**"
      - "setup.cfg"  # includes pytest config
      - "pyproject.toml"  # includes mypy config
    checks:
      - "TODO"
  - id: pytorch_lightning dockers
    paths:
      - "dockers/**"
    checks:
      - "TODO"
  - id: lightning_app
    paths:
      - "TODO"
    checks:
      - "TODO"
  - id: general
    paths:
      - ".github/**"
      - ".pre-commit-config.yaml"
      - "setup.py"
    checks:
      - "TODO"
