# https://docs.drone.io/pipeline/docker/examples/languages/python/#python-example

kind: pipeline
type: docker
name: torch-GPU

steps:

- name: testing
  image: nvcr.io/nvidia/pytorch:20.02-py3
  environment:
    SLURM_LOCALID: 0
    CODECOV_TOKEN:
      from_secret: codecov_token
  #volumes:
  #  # Mount pip cache from host
  #  - name: pip_cache
  #    path: /root/.cache/pip
  commands:
    - python --version
    - pip install pip -U
    - pip --version
    - nvidia-smi
    #- pip install torch==1.3
    - pip install -r requirements.txt --user
    - pip install coverage pytest pytest-cov pytest-flake8 codecov
    - pip install -r ./tests/requirements.txt --user
    - pip list
    - python -c "import torch ; print(' & '.join([torch.cuda.get_device_name(i) for i in range(torch.cuda.device_count())]) if torch.cuda.is_available() else 'only CPU')"
    - coverage run --source pytorch_lightning -m py.test pytorch_lightning tests pl_examples -v --doctest-modules #  --flake8
    - codecov --token $CODECOV_TOKEN  # --pr $DRONE_PULL_REQUEST --build $DRONE_BUILD_NUMBER --branch $DRONE_BRANCH --commit $DRONE_COMMIT --tag $DRONE_TAG

#- name: codecov
#  image: plugins/codecov
#  settings:
#    token: d0fcb731-42af-465d-b680-c1ccdc824bdc
#    files:
#      - *.xml

#volumes:
#  - name: pip_cache
#    host:
#      path: /tmp/cache/drone/pip
