# vim ft=yaml

# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

# See doc/travis_notes.txt for some guidelines

# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

env:
  global:
    - DISPLAY=""

language: python

matrix:
  include:
    - os: linux
      dist: xenial  # Ubuntu 16.04
      python: 3.6
      env: TOXENV=py36
    - os: linux
      dist: bionic  # Ubuntu 18.04
      python: 3.6
      env: TOXENV=py36
    - os: linux
      dist: bionic  # Ubuntu 18.04
      python: 3.7
      env: TOXENV=py37
    - os: osx
      osx_image: xcode9.4
      language: generic
      env:
        - PYTHON=36
        - TOXENV=py36
    - os: osx
      osx_image: xcode9.4
      language: generic
      env:
        - PYTHON=37
        - TOXENV=py37
    - os: windows
      language: minimal
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
      env: TOXENV=py37

# See http://docs.travis-ci.com/user/caching/#pip-cache
cache: pip

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      yes | sudo port install python$PYTHON;
      yes | sudo port install py$PYTHON-pip;
      sudo port select --set python3 python$PYTHON;
      sudo port select --set pip pip$PYTHON;
      export PATH=/Users/travis/Library/Python/$PYTHON/bin:$PATH;
    fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      pip install -r requirements.txt --user;
      pip install -r ./tests/requirements.txt --user;
    else
      pip install -r requirements.txt;
      pip install -r ./tests/requirements.txt;
    fi
  - pip --version ; pip list

script:
  # integration
  - tox --sitepackages
  - python setup.py install --dry-run

after_success:
  - coverage report
  # disable auto coverage bc it isn't accurate since it misses gpu code.
  # to get coverage, run local and push results
  # - codecov

notifications:
  email: false
