# Usage: `conda env update -f environment.yml`
channels:
    - conda-forge
    - pytorch

dependencies:
    - python==3.7.6
    - pip==20.0.2
    - tqdm>=4.35.0
    - numpy>=1.16.4
    - pytorch>=1.1
    - tensorboard>=1.14
    - future>=0.17.1

    # For dev and testing
    - torchvision>=0.4.0, < 0.5  # the 0.5. has some issues with torch JIT
    - tox
    - coverage
    - codecov
    - pytest>=3.0.5
    - pytest-cov
    - pytest-flake8
    - flake8
    - check-manifest
    - twine==1.13.0
    - pillow<7.0.0

    - pip:
        - test-tube>=0.7.5
        - mlflow
        - comet_ml
        - wandb
        - sacred
        - neptune-client
