site_name: Pytorch lightning Documentation
theme: readthedocs
docs_dir: docs
repo_url: https://github.com/williamFalcon/pytorch-lightning
site_dir: 'site'
site_description: 'Documentation for Pytorch Pytorch-Lightning, the researcher version of keras.'

dev_addr: '0.0.0.0:8000'
#google_analytics: ['UA-aasd', 'sitename']
