[build-system]
requires = [
    "setuptools",
    "wheel",
]

[tool.autopep8]
max_line_length = 120
ignore = ["W503", "W504", "E402", "E731", "C40", "E741", "F40", "F841"]

[tool.isort]
known_first_party = [
    "benchmarks",
    "docs",
    "pl_examples",
    "pytorch_lightning",
    "tests",
]
profile = "black"
line_length = 120
force_sort_within_sections = "False"
order_by_type = "False"
