[build-system]
requires = [
    "setuptools",
    "wheel",
]

[tool.isort]
known_first_party = [
    "benchmarks",
    "docs",
    "pl_examples",
    "pytorch_lightning",
    "tests",
]
profile = "black"
line_length = 120
force_sort_within_sections = "False"
order_by_type = "False"

[tool.vulture]
exclude = ['pytorch_lightning/metric/']
make_whitelist = true
min_confidence = 95
paths = ["pytorch_lightning"]
ignore_names = [
    "*idx",
    "*batch",
    "loc",
    "signum",
    "new_dtype",
    "new_device",
    "*_nb",
    "mocked_device_count*",
    "*param*",
    "cmd_line",
    "my_path",
    "torch_save",
    "using_lbfgs",
    "kw",
]
sort_by_size = true
