[build-system]
requires = [
    "setuptools",
    "wheel",
]

[tool.autopep8]
max_line_length = 120
ignore = ["W504", "W504", "E402", "E731", "C40", "E741", "F40", "F841"]

[tool.black]
# https://github.com/psf/black
line-length = 120
target-version = ["py38"]
exclude = "(.eggs|.git|.hg|.mypy_cache|.nox|.tox|.venv|.svn|_build|buck-out|build|dist)"

[tool.isort]
known_first_party = [
    "benchmarks",
    "docs",
    "pl_examples",
    "pytorch_lightning",
    "tests",
]
skip_glob = [
    # todo
    "pytorch_lightning/accelerators/*",


    # todo
    "pytorch_lightning/callbacks/*",


    # todo
    "pytorch_lightning/cluster_environments/*",


    # todo
    "pytorch_lightning/core/*",


    # todo
    "pytorch_lightning/distributed/*",


    # todo
    "pytorch_lightning/metrics/*",


    # todo
    "pytorch_lightning/overrides/*",


    # todo
    "pytorch_lightning/plugins/*",


    # todo
    "pytorch_lightning/profiler/*",


    # todo
    "pytorch_lightning/trainer/*",


    # todo
    "pytorch_lightning/tuner/*",
]
profile = "black"
line_length = 120
force_sort_within_sections = "False"
order_by_type = "False"
