apiVersion: elastic.pytorch.org/v1alpha1
kind: ElasticJob
metadata:
  name: Pytorch Lightning Multi Nodes Testing
  namespace: elastic-job
spec:
  # Use "etcd-service:2379" if you already apply etcd.yaml
  rdzvEndpoint: "etcd-service:2379"
  minReplicas: 2
  maxReplicas: 2
  replicaSpecs:
    Worker:
      replicas: 2
      restartPolicy: ExitCode
      template:
        apiVersion: v1
        kind: Pod
        spec:
          containers:
            - name: Pytorch Lightning Multi Nodes Testing
              image: pytorchlightning/pytorch_lightning:base-cuda-py{PYTHON_VERSION}-torch{PYTORCH_VERSION}
              imagePullPolicy: Always
              command: 
              - bash 
              - -ce
              - | 
                git https://github.com/tchaton/pytorch-lightning.git /repo
                cd /repo
                git fetch --all
                git checkout b07a6dac378459f265f06a256d139b6ab7efa59c
                pip install -e .
                python -m torchelastic.distributed.launch --nproc_per_node={NODES} -m coverage run pytest tests/backends/multi-nodes.py
              resources:
                limits:
                  nvidia.com/gpu: {NODES}