# Pipeline to run the HPU tests in DL1 Instance

trigger:
  tags:
    include:
      - '*'
  branches:
    include:
      - "master"
      - "release/*"
      - "refs/tags/*"

pr:
  - "master"
  - "release/*"

jobs:
  - job: testing
    # how long to run the job before automatically cancelling
    timeoutInMinutes: "10"
    # how much time to give 'run always even if cancelled tasks' before stopping them
    cancelTimeoutInMinutes: "2"
    pool: habana-gaudi-hpus
    container:
      image: "vault.habana.ai/gaudi-docker/1.5.0/ubuntu20.04/habanalabs/pytorch-installer-1.11.0:latest"
      options: "--runtime=habana -e HABANA_VISIBLE_DEVICES=all -e OMPI_MCA_btl_vader_single_copy_mechanism=none --cap-add=sys_nice --net=host --ipc=host --shm-size=4g --name cd-container --privileged -v /dev:/dev -v /usr/bin/docker:/tmp/docker:ro"
      #docker run -it --runtime=habana -e HABANA_VISIBLE_DEVICES=all -e OMPI_MCA_btl_vader_single_copy_mechanism=none --cap-add=sys_nice --net=host --ipc=host vault.habana.ai/gaudi-docker/1.5.0/ubuntu20.04/habanalabs/pytorch-installer-1.11.0:1.5.0-610
      #options: "--shm-size=4g --name cd-container -v /usr/bin/docker:/tmp/docker:ro"
      # From https://docs.habana.ai/en/latest/Installation_Guide/Bare_Metal_Fresh_OS.html#driver-fw-install-bare
    workspace:
      clean: all

    steps:

    - script: |
        /tmp/docker exec -t -u 0 cd-container \
        sh -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -y install sudo"
      displayName: 'Install Sudo in container (thanks Microsoft!)'
    - bash: |
        sudo apt-get install -y hwinfo
        hwinfo --short
        python --version
        sudo pip install pip -U
      displayName: 'Instance HW info'
    - bash: |
        set -e
        pip --version
        sudo pip uninstall -y lightning pytorch-lightning
        pip install fire
        python .actions/assistant.py requirements-prune-pkgs torch,torchvision,torchtext
        pip install ".[extra,test]"
        pip list
      env:
        PACKAGE_NAME: pytorch
        FREEZE_REQUIREMENTS: 1
      displayName: 'Install dependencies'
    - bash: |
        lspci -d 1da3:
        LKD=$(/usr/sbin/lsmod | grep habanalabs | cut -d " " -f12); if [ -z ${LKD} ]; then dmesg -T | tail -1; else printf "Cannot Unload LKD we need to kill the process $LKD\n"
      displayName: 'Check the driver status'
    - bash: |
        python -m pytest -sv accelerators/test_hpu.py --forked --junitxml=hpu1_test-results.xml
      workingDirectory: tests/tests_pytorch
      displayName: 'Single card HPU test'
