# Pipeline to run the HPU tests in DL1 Instance

trigger:
  tags:
    include:
      - '*'
  branches:
    include:
      - "master"
      - "release/*"
      - "refs/tags/*"

pr:
  - "master"
  - "release/*"

jobs:
  - job: testing
    # how long to run the job before automatically cancelling
    timeoutInMinutes: "10"
    # how much time to give 'run always even if cancelled tasks' before stopping them
    cancelTimeoutInMinutes: "2"
    pool: habana-gaudi-hpus
    container:
      image: "vault.habana.ai/gaudi-docker/1.5.0/ubuntu20.04/habanalabs/pytorch-installer-1.11.0:latest"
      options: "--shm-size=4g --name cd-container -v /usr/bin/docker:/tmp/docker:ro" --runtime=habana -e HABANA_VISIBLE_DEVICES=all -e OMPI_MCA_btl_vader_single_copy_mechanism=none --cap-add=sys_nice --net=host --ipc=host 
    workspace:
      clean: all

    steps:

    - script: |
        /tmp/docker exec -t -u 0 cd-container \
        sh -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -y install sudo"
      displayName: 'Install Sudo in container (thanks Microsoft!)'

    - bash: |
        sudo apt-get install -y hwinfo
        hwinfo --short
        python --version
        sudo pip install pip -U
      displayName: 'Instance HW info'

    - bash: |
        set -e
        pip --version
        sudo pip uninstall -y lightning pytorch-lightning
        pip install fire
        python .actions/assistant.py requirements-prune-pkgs torch,torchvision,torchtext
        pip install ".[extra,test]"
        pip list
      env:
        PACKAGE_NAME: pytorch
        FREEZE_REQUIREMENTS: 1
      displayName: 'Install dependencies'

    - bash: |
        lspci -d 1da3:
        ls -al /usr/sbin/
        which hl-fw-loader
        hl-fw-loader -d 19:00.0
        hl-fw-loader -d 1a:00.0
        hl-fw-loader -d 33:00.0
        hl-fw-loader -d 34:00.0
        hl-fw-loader -d b3:00.0
        hl-fw-loader -d b4:00.0
        hl-fw-loader -d cc:00.0
        hl-fw-loader -d cd:00.0
        hl-smi -L
        modinfo habanalabs
        LKD=$(/usr/sbin/lsmod | grep habanalabs | cut -d " " -f12)
        echo "${LKD} is the return value of lkd command"
        process=sudo lsof | grep "dev/hl" | tr -s " " | cut -d" " -f2 | sort -u
        echo "${process} is the list of process"
        /usr/sbin/insmod habanalabs
      displayName: 'Check the driver status'

    - bash: |
        python -m pytest -sv accelerators/test_hpu.py --forked --junitxml=hpu1_test-results.xml
      workingDirectory: tests/tests_pytorch
      displayName: 'Single card HPU test'
