name: Report a bug
description: Any errors that are not UI related.
labels: ["needs triage"]
body:
  - type: textarea
    attributes:
      label: Bug description
      description: A description of the 🐛bug🐛.
    validations:
      required: true
 
  - type: markdown
    attributes:
      value: >
        The rest of this form is optional, but filling it out may help us to provide better support.

  - type: textarea
    attributes:
      label: How to reproduce the bug
      description: >
        Provide steps and example code here.
      placeholder: "# Insert code here"
      render: python
    validations:
      required: false

  - type: textarea
    attributes:
      label: Error messages and logs
      description: >
        Provide any error messages and/or logs
      placeholder: "# Copy the complete error messages and logs"
      value: |
        ```

        # Error messages and logs here please

        ```
    validations:
      required: false

  - type: textarea
    attributes:
      label: Important info
      description: >
        Provide the following info about your environment
      value: |
        ```

        #- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
        #- PyTorch Lightning Version (e.g., 1.5.0):
        #- Lightning App Version (e.g., 0.5.2):
        #- PyTorch Version (e.g., 1.10):
        #- Python version (e.g., 3.9):
        #- OS (e.g., Linux):
        #- CUDA/cuDNN version:
        #- GPU models and configuration:
        #- How you installed Lightning(`conda`, `pip`, source):
        #- Running environment of LightningApp (e.g. local, cloud):

        ```
    validations:
      required: false

  - type: textarea
    attributes:
      label: More info
      description: Add any other info about the issue here.
    validations:
      required: false

  - type: markdown
    attributes:
      value: "**Happy engineering!**"
