blank_issues_enabled: false
contact_links:
  - name: ❓ Ask a Question
    url: https://github.com/Lightning-AI/lightning/discussions/new
    about: Ask and answer Lightning related questions.
  - name: 💬 Chat with us
    url: https://join.slack.com/t/pytorch-lightning/shared_invite/zt-1bqiy6kpt-x~2PBicDp~z_rF8r8l3vcg
    about: Live chat with experts, engineers, and users in our Slack community.
  - name: 📖 Read the documentation
    url: https://lightning.ai/lightning-docs/
    about: Please consult the documentation before opening any issues!
  - name: 🙋 Contact us about professional services
    url: https://lightning.ai
    about: Contact the Lightning.ai sales team for paid support.
