name: Dump local wheels
description: scan local env and dump needed wheels

inputs:
  torch-url:
    description: path to the PyTorch downloads
    required: false
    default: "https://download.pytorch.org/whl/cpu/torch_stable.html"
  wheel-dir:
    description: local path for export wheels
    required: false
    default: ".wheels/"

runs:
  using: "composite"
  steps:

  - name: install dev. env
    run: pip install setuptools wheel
    shell: bash

  - name: Freeze local emv.
    run: |
      pip freeze > requirements.dump
      cat requirements.dump
    shell: bash

  - name: Filter self pkg
    run: |
      fp = 'requirements.dump'
      with open(fp) as fo:
        lines = fo.readlines()
      lines = [ln for ln in lines if '-e ' not in ln]
      with open(fp, 'w') as fw:
        fw.writelines(lines)
    shell: python

  - name: Dump wheels
    run: |
      cat requirements.dump
      pip wheel -r requirements.dump --prefer-binary \
        --wheel-dir=${{ inputs.wheel-dir }} \
        -f=${{ inputs.torch-url }}
      ls -lh ${{ inputs.wheel-dir }}
    shell: bash
