name: Check PR traceability

on:
  push:
    branches: [master, "release/*"]
  pull_request:
    branches: [master, "release/*"]

jobs:
  check-pr-description:
    name: Check PR description
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Check PR validity
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      shell: bash
      run: |
        set -e

        PR_DESCRIPTION=$(gh pr view ${{ env.PR_NUMBER }})

        DEFAULT_DESCRIPTION=$(echo "$PR_DESCRIPTION" | grep -ioE '<issue_number>')

        echo "$DEFAULT_DESCRIPTION"

        if [[ -z "$DEFAULT_DESCRIPTION"]]
        then
          echo "You should reference this PR to an issue and/or other PRs for better traceability."
          exit 1
        fi
