name: Test App

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches: [master, "release/*"]
  pull_request:
    branches: [master, "release/*"]
    paths:
      - ".github/workflows/ci-app-tests.yml"
      - "src/lightning_app/**"
      - "tests/tests_app/**"
      - "requirements/app/**"
      - "setup.py"
      - ".actions/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  FREEZE_REQUIREMENTS: 1

jobs:
  app-pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macOS-11, windows-2022]
        pkg-name: ["", "app"]  # the "" is for installing monolithic package
        python-version: [3.8]
        requires: ["oldest", "latest"]

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: basic setup
        run: pip install -q -r .actions/requirements.txt

      - name: Set min. dependencies
        if: ${{ matrix.requires == 'oldest' }}
        run: python .actions/assistant.py replace_oldest_ver

      - name: switch PyTorch URL
        run: python -c "print('TORCH_URL=https://download.pytorch.org/whl/' + str('test/cpu/torch_test.html' if '${{matrix.release}}' == 'pre' else 'cpu/torch_stable.html'))" >> $GITHUB_ENV
        shell: bash

      - name: Install package
        env:
          PACKAGE_NAME: ${{ matrix.pkg-name }}
        run: |
          pip install -e . pytest --upgrade --find-links ${TORCH_URL}
          pip list
        shell: bash

      - name: DocTests App
        # todo: run doctest laos on mono-package
        if: ${{ matrix.pkg-name != '' }}
        working-directory: src
        run: python -m pytest lightning_app --ignore-glob="**/cli/*-template/**"

      - name: Get pip cache
        id: pip-cache
        run: |
          python -c "from pip._internal.locations import USER_CACHE_DIR; print('::set-output name=dir::' + USER_CACHE_DIR)"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-py${{ matrix.python-version }}-${{ matrix.pkg-name }}-${{ matrix.requires }}-${{ hashFiles('requirements/app/base.txt') }}
          restore-keys: ${{ runner.os }}-pip-py${{ matrix.python-version }}-${{ matrix.pkg-name }}-${{ matrix.requires }}-


      - name: Install dependencies
        env:  # TODO: drop this when we will be using regular releases for testing
            PACKAGE_NAME: pytorch
        run: |
          pip install -r requirements/app/devel.txt --quiet --find-links ${TORCH_URL}
          pip list
        shell: bash

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Adjust tests
        if: ${{ matrix.pkg-name == '' }}
        run: python .actions/assistant.py copy_replace_imports --source_dir="./tests" --source_import="lightning_app" --target_import="lightning.app"

      - name: Tests
        working-directory: ./tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          PYTEST_ARTIFACT: results-${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.requires }}.xml
        run: |
          coverage run --source lightning_app -m pytest -m "not cloud" tests_app --timeout=300 -vvvv --junitxml=$PYTEST_ARTIFACT --durations=50

      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: unittest-results-${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.requires }}
          path: tests/results-${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.requires }}.xml
        if: failure()

      - name: Statistics
        if: success()
        working-directory: ./tests
        run: |
          coverage xml -i
          coverage report -i

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: tests/coverage.xml
          flags: cpu,app,pytest
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false

# TODO: figure out why we clone and install quick-start
#      - name: Clone Quick Start Example Repo
#        uses: actions/checkout@v3
#        # TODO: this needs to be git submodule
#        if: matrix.os == 'windows-2022'  # because the install doesn't work on windows
#        with:
#          repository: Lightning-AI/lightning-quick-start
#          ref: 'main'
#          path: lightning-quick-start
#
#      - name: Lightning Install quick-start
#        shell: bash
#        if: matrix.os != 'windows-2022'  # because the install doesn't work on windows
#        run: |
#          python -m lightning install app lightning/quick-start -y
