on:
  push:
    branches: [master, "release/*"]
    paths:
      - "requirements/pytorch/**"
      - "src/pytorch_lightning/**"
      - "tests/tests_pytorch/**"
      - "setup.cfg"  # includes pytest config
  pull_request:
    branches: [master, "release/*"]
    paths:
      - "requirements/pytorch/**"
      - "src/pytorch_lightning/**"
      - "tests/tests_pytorch/**"
      - "setup.cfg"  # includes pytest config

jobs:
  # https://github.com/marketplace/actions/trigger-circleci-pipeline
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - uses: circleci/trigger_circleci_pipeline@v1
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
