name: Package

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches: [master, "release/*"]
  pull_request:
    branches: [master, "release/*"]
    types: [opened, reopened, ready_for_review, synchronize]  # added `ready_for_review` since draft is skipped
    paths:
      - ".actions/**"
      - ".github/actions/pkg-check/*"
      - ".github/actions/pkg-install/*"
      - ".github/workflows/_build-packages.yml"
      - ".github/workflows/ci-pkg-install.yml"
      - "setup.py"
      - "src/**"
      - "requirements/**"
      - "!requirements/docs.txt"
      - "!requirements/*/docs.txt"
      - "!*.md"
      - "!**/*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/')) }}

defaults:
  run:
    shell: bash

jobs:

  build-packages:
    uses: ./.github/workflows/_build-packages.yml
    with:
      artifact-name: dist-packages-${{ github.sha }}

  install-pkg:
    needs: build-packages
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macOS-12, windows-2022]
        pkg-name: ["app", "lite", "pytorch", "lightning", "notset"]
        python-version: ["3.7" , "3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/download-artifact@v3
        with:
          name: dist-packages-${{ github.sha }}
          path: dist

      - uses: ./.github/actions/pkg-install
        with:
          pkg-name: ${{ matrix.pkg-name }}
          pip-flags: "-f dist"

      - name: Run CLI (via python)
        if: ${{ matrix.pkg-name == 'lightning' || matrix.pkg-name == 'notset' }}
        run: python -m lightning --version
      - name: Run CLI (direct bash)
        if: ${{ matrix.pkg-name == 'lightning' || matrix.pkg-name == 'app' }}
        run: lightning --version

      - name: DocTests actions
        working-directory: .actions/
        run: |
          pip install -q pytest
          python -m pytest setup_tools.py
      - name: DocTest package
        env:
          LIGHTING_TESTING: 1  # path for require wrapper
          PY_IGNORE_IMPORTMISMATCH: 1
        run: |
          pip install -q "pytest-doctestplus>=0.9.0"
          pip list
          PKG_NAME=$(python -c "print({'app': 'lightning_app', 'lite': 'lightning_lite', 'pytorch': 'pytorch_lightning'}.get('${{matrix.pkg-name}}', 'lightning'))")
          python -m pytest src/${PKG_NAME} --ignore-glob="**/cli/*-template/**"
