name: Check Schema

on:
  push: {}
  pull_request:
    branches: [master, "release/*"]

jobs:
  check:
    uses: ./.github/workflows/_check-schema.yml
    with:
      # skip azure due to the wrong schema file by MSFT
      # https://github.com/Lightning-AI/lightning-flash/pull/1455#issuecomment-1244793607
      azure-dir: ''
