name: Test Fabric

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches: [master, "release/*"]
  pull_request:
    branches: [master, "release/*"]
    types: [opened, reopened, ready_for_review, synchronize]  # added `ready_for_review` since draft is skipped
    paths:
      - ".actions/**"
      - "requirements/fabric/**"
      - "src/lightning_fabric/**"
      - "tests/tests_fabric/**"
      - "pyproject.toml"  # includes pytest config
      - ".github/workflows/ci-tests-fabric.yml"
      - "!requirements/*/docs.txt"
      - "!*.md"
      - "!**/*.md"
  schedule:
    # At the end of every day
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/')) }}

defaults:
  run:
    shell: bash

jobs:
  fabric-cpu:
    runs-on: ${{ matrix.os }}
    if: github.event.pull_request.draft == false
    strategy:
      fail-fast: false
      matrix:
        include:
          # assign python and pytorch version combinations to operating systems (arbitrarily)
          # note: there's no distribution of torch==1.10 for Python>=3.10
          - {os: "macOS-11", pkg-name: "fabric", python-version: "3.8", pytorch-version: "1.11"}
          - {os: "macOS-11", pkg-name: "fabric", python-version: "3.9", pytorch-version: "1.12"}
          - {os: "ubuntu-20.04", pkg-name: "fabric", python-version: "3.8", pytorch-version: "1.10"}
          - {os: "ubuntu-20.04", pkg-name: "fabric", python-version: "3.9", pytorch-version: "1.11"}
          - {os: "ubuntu-20.04", pkg-name: "fabric", python-version: "3.10", pytorch-version: "1.12"}
          - {os: "windows-2022", pkg-name: "fabric", python-version: "3.9", pytorch-version: "1.11"}
          - {os: "windows-2022", pkg-name: "fabric", python-version: "3.10", pytorch-version: "1.12"}
          # only run PyTorch latest with Python latest
          - {os: "macOS-11", pkg-name: "fabric", python-version: "3.10", pytorch-version: "1.13"}
          - {os: "ubuntu-20.04", pkg-name: "fabric", python-version: "3.10", pytorch-version: "1.13"}
          - {os: "windows-2022", pkg-name: "fabric", python-version: "3.10", pytorch-version: "1.13"}
          # "oldest" versions tests, only on minimum Python
          - {os: "macOS-11", pkg-name: "fabric", python-version: "3.7", pytorch-version: "1.10", requires: "oldest"}
          - {os: "ubuntu-20.04", pkg-name: "fabric", python-version: "3.7", pytorch-version: "1.10", requires: "oldest"}
          - {os: "windows-2022", pkg-name: "fabric", python-version: "3.7", pytorch-version: "1.10", requires: "oldest"}
          # "lightning" installs the monolithic package
          - {os: "macOS-11", pkg-name: "lightning", python-version: "3.8", pytorch-version: "1.13"}
          - {os: "ubuntu-20.04", pkg-name: "lightning", python-version: "3.8", pytorch-version: "1.13"}
          - {os: "windows-2022", pkg-name: "lightning", python-version: "3.8", pytorch-version: "1.13"}
          # pytorch 2.0 Tests
          - {os: "macOS-11", pkg-name: "fabric", python-version: "3.10", pytorch-version: "2.0"}
          - {os: "ubuntu-20.04", pkg-name: "fabric", python-version: "3.10", pytorch-version: "2.0"}
          - {os: "windows-2022", pkg-name: "fabric", python-version: "3.10", pytorch-version: "2.0"}

    timeout-minutes: 25  # because of building grpcio on Mac
    env:
      PACKAGE_NAME: ${{ matrix.pkg-name }}
      TORCH_URL: "https://download.pytorch.org/whl/cpu/torch_stable.html"
      FREEZE_REQUIREMENTS: ${{ ! (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/')) }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: basic setup
      run: pip install -q -r .actions/requirements.txt

    - name: Set min. dependencies
      if: ${{ matrix.requires == 'oldest' }}
      run: python .actions/assistant.py replace_oldest_ver

    - name: Adjust PyTorch versions in requirements files
      if: ${{ matrix.requires != 'oldest' }}
      run: |
        for fpath in `ls requirements/**/*.txt`; do \
          python ./requirements/pytorch/adjust-versions.py $fpath ${{ matrix.pytorch-version }}; \
        done
        cat requirements/fabric/base.txt

    - name: Get pip cache dir
      id: pip-cache
      run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

    - name: pip cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: pip-${{ matrix.pkg-name }}-${{ matrix.release }}-${{ matrix.requires }}-${{ hashFiles('requirements/fabric/*.txt') }}
        restore-keys: pip-${{ matrix.pkg-name }}-${{ matrix.release }}-
        enableCrossOsArchive: true

    - name: Env. variables
      run: |
        # Switch coverage scope
        python -c "print('COVERAGE_SCOPE=' + str('lightning' if '${{matrix.pkg-name}}' == 'lightning' else 'lightning_fabric'))" >> $GITHUB_ENV

    - name: Install package & dependencies
      run: |
        pip install -e .[test] \
          "pytest-timeout" -r requirements/fabric/strategies.txt \
          -U --find-links ${TORCH_URL}
        pip list

    - name: Adjust tests
      if: ${{ matrix.pkg-name == 'lightning' }}
      run: |
        python .actions/assistant.py copy_replace_imports --source_dir="./tests" \
          --source_import="lightning_fabric" --target_import="lightning.fabric"

    - name: Testing Warnings
      # the stacklevel can only be set on >=3.7
      if: matrix.python-version != '3.7'
      working-directory: tests/tests_fabric
      # needs to run outside of `pytest`
      run: python utilities/test_warnings.py

    - name: Switch coverage scope
      run: python -c "print('COVERAGE_SCOPE=' + str('lightning' if '${{matrix.pkg-name}}' == 'lightning' else 'lightning_fabric'))" >> $GITHUB_ENV

    - name: Testing Fabric
      working-directory: tests/tests_fabric
      # NOTE: do not include coverage report here, see: https://github.com/nedbat/coveragepy/issues/1003
      run: |
        python -m coverage run --source ${{ env.COVERAGE_SCOPE }} \
          -m pytest -v --timeout=30 --durations=50

    - name: Statistics
      if: success()
      working-directory: tests/tests_fabric
      run: |
        coverage report
        coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      # see: https://github.com/actions/toolkit/issues/399
      continue-on-error: true
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: tests/tests_fabric/coverage.xml
        flags: ${{ env.COVERAGE_SCOPE }},cpu,pytest,python${{ matrix.python-version }}
        name: CPU-coverage
        fail_ci_if_error: false
