name: Milestone
on: [issues, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Check if milestone is set
      id: milestone-check
      uses: scholzj/milestone-check-action@v1
      with:
        status_context: 'Milestone Check'
        token: ${{ secrets.GITHUB_TOKEN }}
