name: Package

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches: [master, "release/*"]
  pull_request:
    branches: [master, "release/*"]
    paths-ignore:
      - "src/lightning_app/**"  # todo: implement job skip

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/')) }}

defaults:
  run:
    shell: bash

jobs:

  init-dist:
    runs-on: ubuntu-20.04
    steps:
    - run: mkdir dist && touch dist/.placeholder
    - uses: actions/upload-artifact@v3
      with:
        name: ci-packages-${{ github.sha }}
        path: dist

  install-standalone:
    needs: init-dist
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        os: [ubuntu-20.04, macOS-10.15, windows-2019]
        pkg: ["app", "pytorch"]  # todo: add following use-case "lightning" after resowing pulling sources
        # in fact, lest make this se depending jobs, at fist build app and pytorch, and save these packages as artefact
        # then, in the following job pull artefacts and install these packages and build and test lightning
        # todo: in such case abstract this pkg testing as actions to reduce variation in testing
        python-version: [3.7]  # , 3.9

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/download-artifact@v3
        with:
          name: ci-packages-${{ github.sha }}
          path: dist
      - run: ls -lh dist/

      - uses: ./.github/actions/pkg-check
        with:
          pkg-name: ${{ runner.pkg }}

      - uses: actions/upload-artifact@v3
        with:
          name: ci-packages-${{ github.sha }}
          path: dist

      - name: Determine package name
        if: ${{ inputs.pkg-import == '' }}
        working-directory: ./dist
        run: python -c "import glob ; ls = glob.glob('*.tar.gz') ; name = '_'.join(ls[0].split('-')[:-1]) ; print(f'PKG_NAME={name}')" >> $GITHUB_ENV

      - uses: ./.github/actions/pkg-install
        with:
          pkg-name: ${{ env.PKG_NAME }}

