name: Multi Nodes GPU tests

# Workflow Steps:
#  1. Set IMAGETAG
#  2. Configure AWS Credentials
#  3. Configure Docker and Push to ECR
#  5. Install EKSClient
 # 6. Clone Elastic repo
#  7. Create node group
#  8. Apply elastic kukeclt cmd
#  9. Launch multi-node-test.yaml
#      - Create a tests/backends/test_multi_nodes.py file
#  10. Use kukeclt to get logs
#  11. Print logs
#  12. Upload coverage.

#on:
#  pull_request:
#    branches: [master, "release/1.0.x"]  # include release branches like release/1.0.x
#    types: [closed]

on: push

env:
  NODE_TYPE: p3.8xlarge
  NODES: 2

jobs:
  setup-build-test-publish:
    name: multi-nodes-gpu-testing
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
        pytorch-version: [1.5]
    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 50

    # runs only when merged happened.
    #if: github.event.pull_request.merged == true
    steps:

    - name: Checkout Pytorch Lightning
      uses: actions/checkout@v2
      with:
        repository: tchaton/pytorch-lightning
        ref: ${{ github.event.base_ref }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set IMAGETAG
      #run: echo "IMAGETAG=${{ github.event.pull_request.head.sha }}${{ matrix.python-version }}" >> $GITHUB_ENV
      run: |
        echo "IMAGETAG=${{ github.event.base_ref }}${{ matrix.python-version }}" >> $GITHUB_ENV

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCES_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
        aws-region: us-east-2

    #- uses: whoan/docker-build-with-cache-action@v5
    #  with:
    #    registry: ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.us-east-2.amazonaws.com
    #    image_name: multi-nodes-gpu-testing
    #    image_tag: ${{ github.event.base_ref }}${{ matrix.python-version }}
    #    push_git_tag: true
    #    dockerfile: ./dockers/multi-gpu-tests/Dockerfile
    #    build_extra_args: "--build-arg PYTHON_VERSION=${{ matrix.python-version }}"

    - name: Configure AWS Credentials
      run: |
        python -c "fname = './.github/multi-nodes/multi-nodes-gpu.yaml' ; req = open(fname).read().replace('{{PYTHON_VERSION}}}', '${{ matrix.python-version }}').replace('{{PYTORCH_VERSION}}}', '${{ matrix.pytorch-version }}').replace('{NODES}', '$NODES') ; open(fname, 'w').write(req)"
        python -c "fname = './.github/multi-nodes/multi-nodes-gpu.yaml' ; print(open(fname).read())"          

    - name: Install EKSClient
      run: |
        curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
        sudo mv /tmp/eksctl /usr/local/bin
      shell: bash

    - name: Clone TorchElastic
      run: |
        git clone https://github.com/pytorch/elastic.git
      shell: bash