name: Multi Nodes GPU tests

# Workflow Steps:
#  1. Set IMAGETAG
#  3. Edit multi-node-test.yaml template to refer to IMAGETAG
#  4. Connect to AWS
#  5. Install EKSClient
 # 6. Clone Elastic repo
#  7. Create node group
#  8. Apply elastic kukeclt cmd
#  9. Launch multi-node-test.yaml
#      - Create a tests/backends/test_multi_nodes.py file
#  10. Use kukeclt to get logs
#  11. Print logs
#  12. Upload coverage.

#on:
#  pull_request:
#    branches: [master, "release/1.0.x"]  # include release branches like release/1.0.x
#    types: [closed]

on: push

env:
  AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
  AWS_ACCES_KEY_ID: ${{ secrets.AWS_ACCES_KEY_ID }}
  AWS_SECRET_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_CLUSTER: ${{ secrets.AWS_CLUSTER }}
  IMAGE_NAME: ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/{{ secrets.AWS_CLUSTER }}
  NODE_TYPE: p3.8xlarge
  NODES: 2

jobs:
  setup-build-publish-deploy:
    name: multi-node-testing-job
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7]
    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 50

    # runs only when merged happened.
    if: github.event.pull_request.merged == true
    steps:

    - name: Set IMAGETAG
      run: echo "IMAGETAG=${{ github.event.pull_request.head.sha }}_${{ matrix.python-version }}" >> $GITHUB_ENV

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: $AWS_ACCES_KEY_ID
        aws-secret-access-key: $AWS_SECRET_KEY_ID
        aws-region: $AWS_REGION