name: TPU tests

# Workflow Steps:
#  1. Setup gcloud CLI
#  2. Checkout Pytorch Lightning
#  3. Set up Python
#  4. Set up Python 3.7
#  5. Get Current PR Number
#  6. Checkout ml-testing-accelerators
#  7. Install jsonnet
#  8. Get Cluster Credentials
#  9. Deploy the job on the kubernetes cluster
#  10. Statistics
#  11. Upload coverage results
#  12. Upload coverage to Codecov

on:
  push:
    branches: [master, "release/*"]

env:
  GKE_CLUSTER: lightning-cluster
  GKE_ZONE: us-central1-a
  MAX_CHECKS: 360
  CHECK_SPEEP: 5

jobs:
  setup-deploy:
    name: tpu-testing-job
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
        xla-version: [1.6, 1.8]
    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 50

    steps:
    - name: Setup gcloud CLI
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GKE_SA_KEY_BASE64 }}
        project_id: ${{ secrets.GKE_PROJECT }}
        export_default_credentials: true

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Get Current PR & SHA Number
      id: vars
      shell: bash
      run: |
        echo ::set-output name=PR_NUMBER::$(git ls-remote origin "pull/*/head" | grep -F -f <(git rev-parse HEAD) | awk -F'/' '{print $3}')
        echo "::set-output name=SHA::$(git rev-parse --short HEAD)"

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Checkout ml-testing-accelerators
      uses: actions/checkout@v2
      with:
        repository: GoogleCloudPlatform/ml-testing-accelerators
        path: ml-testing-accelerators
        ref: 5e88ac24f631c27045e62f0e8d5dfcf34e425e25

    - name: Install jsonnet
      run: |-
        go get github.com/google/go-jsonnet/cmd/jsonnet
      shell: bash

    # Get the GKE credentials so we can deploy to the cluster
    # Use either zone or region depending on cluster setup.
    - name: Get Cluster Credentials
      run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
      shell: bash

    - name: Update jsonnet file
      run: |-
        fname = 'dockers/tpu-tests/tpu_test_cases.jsonnet'
        tt = open(fname).read()
        tt = tt.replace('{PYTORCH_VERSION}', '$XLA_VER')
        tt = tt.replace('{PYTHON_VERSION}', '$PYTHON_VER')
        tt = tt.replace('{PR_NUMBER}', '${{ steps.vars.outputs.PR_NUMBER }}')
        tt = tt.replace('{SHA}', '${{ steps.vars.outputs.SHA }}')
        open(fname, 'w').write(ttt)
      shell: python

    - name: Deploy the job on the kubernetes cluster
      env:
        XLA_VER: ${{ matrix.xla-version }}
        PYTHON_VER: ${{ matrix.xla-version }}
      run: |-
        cat dockers/tpu-tests/tpu_test_cases.jsonnet
        job_name=$(jsonnet -J ml-testing-accelerators/ dockers/tpu-tests/tpu_test_cases.jsonnet | kubectl create -f -) && \
        job_name=${job_name#job.batch/} && \
        job_name=${job_name% created} && \
        echo "Waiting on kubernetes job: $job_name in cluster: $GKE_CLUSTER" && \
        i=0 && \
        # 60 checks spaced 30s apart = 900s total.
        status_code=2 && \
        # Check on the job periodically. Set the status code depending on what
        # happened to the job in Kubernetes. If we try MAX_CHECKS times and
        # still the job hasn't finished, give up and return the starting
        # non-zero status code.
        printf "Waiting for job to finish: " && \
        while [ $i -lt $MAX_CHECKS ]; do ((i++)); if kubectl get jobs $job_name -o jsonpath='Failed:{.status.failed}' | grep "Failed:1"; then status_code=1 && break; elif kubectl get jobs $job_name -o jsonpath='Succeeded:{.status.succeeded}' | grep "Succeeded:1" ; then status_code=0 && break; else printf "." ; fi; sleep $CHECK_SPEEP; done && \
        echo "Done waiting. Job status code: $status_code" && \
        pod_name=$(kubectl get po -l controller-uid=`kubectl get job $job_name -o "jsonpath={.metadata.labels.controller-uid}"` | awk 'match($0,!/NAME/) {print $1}') && \
        echo "GKE pod name: $pod_name" && \
        kubectl logs -f $pod_name --container=train > /tmp/full_output.txt
        if grep -q '<?xml version="1.0" ?>' /tmp/full_output.txt ; then csplit /tmp/full_output.txt '/<?xml version="1.0" ?>/'; else mv /tmp/full_output.txt xx00; fi && \
        # First portion is the test logs. Print these to Github Action stdout.
        cat xx00 && \
        echo "Done with log retrieval attempt." && \
        echo "Status code: $status_code"
        exit $status_code
      shell: bash

    - name: Statistics
      if: success()
      run: |
        mv ./xx01 coverage
        # TODO: add human readable report
        cat coverage
        #  sudo pip install pycobertura
        #  pycobertura show coverage.xml

    - name: Upload coverage results
      uses: actions/upload-artifact@v2
      with:
        name: coverage-TPU
        path: coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      # see: https://github.com/actions/toolkit/issues/399
      continue-on-error: true
      if: always()
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage
        flags: tpu,pytest
        name: TPU-coverage
        fail_ci_if_error: true
