name: Code check

on:
  push:
    branches: [master, "release/*"]
  pull_request:
    branches: [master, "release/*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/')) }}

env:
  FREEZE_REQUIREMENTS: "1"

defaults:
  run:
    shell: bash

jobs:

  build-pypi:
    # This serves to create packages for potential internal dependencies
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Build package
        env:
          PACKAGE_NAME: "lite"
        run: python setup.py sdist
      - uses: actions/upload-artifact@v3
        with:
          name: ci-packages-${{ github.sha }}
          path: dist

  mypy:
    needs: build-pypi
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: ci-packages-${{ github.sha }}
        path: pypi

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10.6'

    # Note: This uses an internal pip API and may not always work
    # https://github.com/actions/cache/blob/master/examples.md#multiple-oss-in-a-workflow
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements/pytorch/base.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      env:  # TODO: drop this when we will be using regular releases for testing
        PACKAGE_NAME: pytorch
      run: |
        pip install mypy==0.982
        pip install torch==1.12 --find-links https://download.pytorch.org/whl/cpu/torch_stable.html
        python ./requirements/pytorch/adjust-versions.py requirements/pytorch/extra.txt
        # todo: adjust requirements for both code-bases
        pip install \
          -r requirements/pytorch/devel.txt \
          -r requirements/app/devel.txt \
          -r requirements/lite/devel.txt \
          --find-links https://download.pytorch.org/whl/cpu/torch_stable.html \
          --find-links pypi
        pip list

    - name: Check typing
      run: |
        mkdir .mypy_cache
        mypy
