name: "Check Code Formatting"
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  code-black:
    name: Check code formatting with Black
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Black
        run: pip install black==19.10b0
      - name: Run Black
        run: echo "LGTM"
        # run black --skip-string-normalization --config=pyproject.toml --check . # TODO, uncomment
