on:
  push:
    branches: [ master, "release/*" ]

jobs:

  # This label will then be managed by this action.
  #  It will be added to PRs with merge conflicts and removed from PRs without conflicts.
  #  https://github.com/mschilde/auto-label-merge-conflicts
  label-conflicts:
    runs-on: ubuntu-20.04
    steps:
      - uses: mschilde/auto-label-merge-conflicts@v2
        with:
          CONFLICT_LABEL_NAME: "has conflicts"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_RETRIES: 5
          WAIT_MS: 5000
