name: Check Markdown links
# https://github.com/gaurav-nelson/github-action-markdown-link-check

on:
  push:
    branches: [master, "release/*"]
  pull_request:
    branches: [master, "release/*"]
    types: [opened, reopened, ready_for_review, synchronize]
    paths:
      - "**/*.md"

jobs:
  markdown-link-check:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
