name: PyPI

# https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push: {}  # FIXME
#    branches: [master, "release/*"]
  release:
    types: [published]

jobs:
  init:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - run: |
        mkdir dist && touch dist/.placeholder
    - uses: actions/upload-artifact@v3
      with:
        name: dist-packages-${{ github.sha }}
        path: dist

  build-packages:
    needs: init
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      # run sequential
      max-parallel: 1
      matrix:
        pkg-name: ["lightning", "app", "lite", "pytorch"]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: dist-packages-${{ github.sha }}
        path: dist
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -U setuptools wheel

    - name: Build packages
      env:
        PACKAGE_NAME: ${{ matrix.pkg-name }}
      run: |
        python setup.py sdist bdist_wheel
        ls -lh dist/

    - uses: actions/upload-artifact@v3
      with:
        name: dist-packages-${{ github.sha }}
        path: dist

  upload-packages:
    runs-on: ubuntu-20.04
    needs: build-packages
    if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: dist-packages-${{ github.sha }}
        path: dist
    - run: ls -lh dist/
    - name: Upload to release
      uses: AButler/upload-release-assets@v2.0
      with:
        files: 'dist/*'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

  signaling:
    runs-on: ubuntu-20.04
    needs: build-packages  # TODO: this shall be `upload-packages`
    steps:
    - uses: actions/checkout@v3
      with:
        repository: gridai/base-images
        token: ${{ secrets.PAT_GHOST }}
        ref: master
    - uses: fregante/setup-git-token@v1
      with:
        token: ${{ secrets.PAT_GHOST }}
        name: PL Ghost
        email: pl-github@grid.ai
    - run: ls -l
    # TODO bump version
    - run: |
        import json
        with open("versions.json") as fo:
            vers = json.load(fo)
        print(vers)
    - name: GIT Commit
      run: |
        git add versions.json
        git status
        git commit -m "bumping version TBD"
        git push

  waiting:
    runs-on: ubuntu-20.04
    needs: build-packages
    steps:
    - name: Delay releasing
      uses: juliangruber/sleep-action@v1
      with:
        time: 30m

  publish-packages:
    runs-on: ubuntu-20.04
    needs: [waiting, signaling]
    if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: dist-packages-${{ github.sha }}
        path: dist
    - run: ls -lh dist/
    - run: mkdir pypi/

    - uses: ./.github/actions/pkg-publish
      with:
        pkg-pattern: "*app*"
        pypi-token: ${{ secrets.PYPI_TOKEN_APP }}
    - uses: ./.github/actions/pkg-publish
      with:
        pkg-pattern: "*lite*"
        pypi-token: ${{ secrets.PYPI_TOKEN_LITE }}
    - uses: ./.github/actions/pkg-publish
      with:
        pkg-pattern: "*pytorch*"
        pypi-token: ${{ secrets.PYPI_TOKEN_PYTORCH }}
    - uses: ./.github/actions/pkg-publish
      with:
        pkg-pattern: "*"
        pypi-token: ${{ secrets.PYPI_TOKEN_LAI }}

  legacy-checkpoints:
    needs: publish-packages
    uses: ./.github/workflows/legacy-checkpoints.yml
    with:
      push_to_s3: true
      create_pr: true
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}
