name: Test PyTorch - TPU

on:
  push:
    branches: [master, "release/*"]
  pull_request:  # TODO: set to target later
    branches: [master, "release/*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/')) }}

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: lightning-cluster
  GKE_ZONE: us-central1-a

defaults:
  run:
    shell: bash

jobs:
  test-on-tpus:
    runs-on: ubuntu-22.04
    # run only when merged to master or the PR title contains '[TPU]'
    if: ${{ github.event.pull_request.merged == true || contains(github.event.pull_request.title, '[TPU]') }}
    env:
      PYTHON_VER: 3.8
    strategy:
      fail-fast: false
      matrix:
        pkg-name: ["fabric", "pytorch"]
    # 1 hour is the access token lifetime: https://cloud.google.com/docs/authentication/token-types#at-lifetime
    timeout-minutes: 60  # should match the timeout in the jsonnet files

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VER }}

    - uses: actions/setup-go@v4
      with:
        go-version: '1.19'

    - uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GKE_SA_KEY_BASE64 }}

    # https://docs.github.com/en/actions/deployment/deploying-to-your-cloud-provider/deploying-to-google-kubernetes-engine
    - uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    - name: Cleanup
      if: always()
      shell: bash
      run: |
        # delete the job, this will also delete the associated pod
        kubectl delete job --all
        kubectl delete pod --all
        # show all resources
        kubectl get pods
        kubectl get jobs
